--- #YAML:1.0
name:               Directory-Iterator
version:            1
abstract:           Simple, efficient way to get a list of file
author:
    - Steve Sanbeg
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Directory::Iterator::PP:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
